### ISSUE TITLE
navigation token wiki not good

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_tokens#2]
![image](https://user-images.githubusercontent.com/6021844/41698616-ac67839e-751f-11e8-8784-7e25fe4c6d05.png)

put nice structure in place, make logic

**Comment by despiegk** [comment]
navigation is now worse, all flat?

![image](https://user-images.githubusercontent.com/6021844/41807655-3baf3d72-76d2-11e8-9cc1-c7b080df26d9.png)

**Comment by nbabenko** [comment]
@yveskerwyn , looks like you updated the sidebar, can you please take a look, it feels like its missing some parts of the wiki now in navigation

**Comment by yveskerwyn** [comment]
Actually, it is not flat, when you click Technology or How To for instance, you go down one level, and you can go up again, by click Home, it is implemented in all wikis like this

I will make the menu better today (Monday) - and report back here, thanks for your feedback than

**Comment by Ibizapowerspot** [comment]
All the parts are still there, ( except for the comment line wallet, there was nothing behind that, can be adapted later)  it is a bit more logical now for a reader that is new to ThreeFold and more condensed.

**Comment by yveskerwyn** [comment]
https://threefoldfoundation.github.io/info_tokens/#/technology/command_line_wallet moved under Technology since this is rather techie and not to relevant for an average wiki visitor

**Comment by yveskerwyn** [comment]
Let's now also update the first page, as requested in #1
