### ISSUE TITLE
need to get all faq's related to tokens on the wiki

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_tokens#4]

**Comment by yveskerwyn** [comment]
I'm trying to find out where all FAQs are, I only know about these: https://threefoldfoundation.github.io/info_foundation/#/faq/README

**Comment by yveskerwyn** [comment]
Just also found this: https://github.com/threefoldfoundation/info_grid/blob/master/docs/faq/faq_3.md

**Comment by yveskerwyn** [comment]
Currently this is what we have, three cross-linked Wiki's, with consistent navigation experience:
- - https://threefoldfoundation.github.io/info_foundation/#/faq/README
- https://threefoldfoundation.github.io/info_grid/#/faq/README
- https://threefoldfoundation.github.io/info_tokens/#/faq/README

**Comment by yveskerwyn** [comment]
The last one is the about tokens, and all token-specific wikis are there, some of them are embedded into the other two wikis
