### ISSUE TITLE
finalize IEO round 1 ecosystem participation list

### ISSUE THREAD

**Issue by AdnanFatayerji** [threefoldfoundation/info_tokens#44]
IEO Ecosystem Participation List https://docs.google.com/spreadsheets/d/1fpIQeI_UZ5y09I0JW89zNc_PT6-Lgpnd8b8_7tpNbGA/edit#gid=0

**Comment by Sacha96** [comment]
@AdnanFatayerji please provide update on this list for TDE. Regards.
