### ISSUE TITLE
Break of token dynamics:  token amounts /liquid/circulating/locked/locking schedule/IEO pricing/total existence/ etc

### ISSUE THREAD

**Issue by AdnanFatayerji** [threefoldfoundation/info_tokens#46]
https://docs.google.com/document/d/1CDT-I1eLLXrKBput7I3cxH89W8WPKL_x7S0Lm8_5ECQ/edit

**Comment by Sacha96** [comment]
@AdnanFatayerji please define the status of this document. We recommend moving it to the wiki. Regards.
