### ISSUE TITLE
farming info should not be on token website

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_tokens#5]
![image](https://user-images.githubusercontent.com/6021844/41807715-4911367c-76d3-11e8-920e-95ae77dbc80e.png)

**Comment by despiegk** [comment]
can link to farming for sure & explain what farming is

**Comment by yveskerwyn** [comment]
On the [How to buy tokens](https://threefoldfoundation.github.io/info_tokens/#/how_to_buy/README) page there is a link to to farming:
```
Next to buying ThreeFold tokens, you can also earn ThreeFold tokens as a ThreeFold Farmer, as documented in the [ThreeFold Grid Wiki](https://threefoldfoundation.github.io/info_grid/#/).
```
