### ISSUE TITLE
wording issues on https://wiki.tokens.grid.tf/#/ 

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_tokens#53]
On homepage: https://wiki.tokens.grid.tf/#/

1st error: You are invited to contribute to this wiki by directly editing the sources files or by creating a issue with feedback or a change request on the info_tokens GitHub repository.

'a' issue -> should be 'an' issue

2nd error Next to this wiki, we have three additional Wiki that you might want to checkout:

three addintional 'Wiki' -> should be three additional 'Wikis'

**Comment by Sacha96** [comment]
On what are threefold Tokens page: https://wiki.tokens.grid.tf/#/what_are_tfts

thus expending the usable Grid. Therefor no central entity controls the internet

ThreeFold Capacity can be used for anything, for instance for storage or computing power, which can be used for any workload.

In Rivine section:

**Comment by Sacha96** [comment]
On what are threefold Tokens page: https://wiki.tokens.grid.tf/#/what_are_tfts

1st error: thus 'expending' the usable Grid. 'Therefor' no central entity controls the internet
should be: thus 'expanding' the usable Grid. 'Therefore' no central entity controls the internet

2nd issue: ThreeFold Capacity can be used for anything, for instance for storage or computing power, which can be used for any workload.
Should be: ThreeFold Capacity can be used for anything, for instance for storage, computing or any kind of workload.

In Rivine section:

 it is endlessly scalable thanks for the farmers joining the Grid.

**Comment by Sacha96** [comment]
https://wiki.tokens.grid.tf/#/how_to_buy/mazraa?id=buy-from-mazraa-farm

1st error: Mazraa is one of the first farmers on the ThreeFold grid. It is possible to buy ThreeFold 'toknes' from Mazraa farm by
Should be: Mazraa is one of the first farmers on the ThreeFold grid. It is possible to buy ThreeFold 'tokens' from Mazraa farm by

2nd error: 7. Wait until your 'documetns' are approved.
Should be: 7. Wait until your 'documents' are approved.

**Comment by Sacha96** [comment]
[https://wiki.tokens.grid.tf/#/how_to_buy/btc-alpha](url)

Deposit BTC section

1st error: First we will transfer Bitcoins to your BTC wallet at BTC-Alpha, which we will then 'use' to buy TFT.
Should be: First we will transfer Bitcoins to your BTC wallet at BTC-Alpha, which we will then 'be used' to buy TFT.

2nd error: You can use this address from any other online cryptocurrency exchange ...... deposit fiat money and 'by buy' Bitcoins.
Should ne: deposit fiat money and 'buy' Bitcoins

Withdraw TFT section 

3rd error: in image describing transaction it quotes: amount should be greather than 
should be: amount should be greater than

**Comment by Sacha96** [comment]
https://wiki.tokens.grid.tf/#/threefold_app

Using the ThreeFold App section

1st error: Follow the steps below in order to setup your ThreeFold wallet, 'and' receive and send your first ThreeFold tokens:
Should be: ....ThreeFold wallet, receive and send your first ThreeFold tokens:

**Comment by Sacha96** [comment]
https://wiki.tokens.grid.tf/#/token_issuance_economy

Value of the token page - Token issuance economy section

Error: 5. When somebody wants to run workloads on farmer’s hardware, in order to reserve capacity he should use TFT. After reservation, TFT goes back to farmer.
Should be: When somebody wants to run workloads on farmer's hardware, TFT should be used to reserve capacity. 

Note: he shouldn't be used as it implies its directed only to men. He/she is not deemed as a solution as then it becomes LGBTQ unfriendly (they). Therefore, either avoid it completely or put he/she/they.

**Comment by zaibon** [comment]
@Sacha96 all the content you are referring to is actually present in this same repository.
Example:

> 1st error: You are invited to contribute to this wiki by directly editing the sources files or by creating a issue with feedback or a change request on the info_tokens GitHub repository.

This sentence is from this file: https://github.com/threefoldfoundation/info_tokens/blob/master/docs/README.md

I think it would be more efficient if you would propose a pull request with all the mistake your found corrected, then just creating a comment for each and waiting for someone else to fix it.

**Comment by Sacha96** [comment]
@zaibon thank you for your proposal. I'll try to do as you explained. Warm regards
